[
    {
      "id": 1,
      "title": "Scientists discover new species of bird in the Amazon rainforest",
      "category": "National News",
      "author": "John Smith",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-12",
      "description": "Researchers have identified a new species of bird in the Amazon rainforest, marking a significant discovery in biodiversity.",
      "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac purus ac tellus gravida fringilla. Nam non nunc vel sapien rhoncus aliquet. Sed in sapien ut purus posuere mollis. Nunc non dui aliquet, efficitur sem vitae, volutpat nisi. Proin non magna ac felis lobortis condimentum vel at nisi. Cras at lobortis ex, a pharetra eros. Nulla hendrerit ultricies libero a tempor. Integer in rutrum tortor, ac faucibus libero. Fusce volutpat metus quam, ac malesuada turpis consequat id.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.5,
      "total_views": 15000
    },
    {
      "id": 2,
      "title": "New study suggests benefits of meditation for mental health",
      "category": "National News",
      "author": "Emily Johnson",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-10",
      "description": "A recent study published in a leading medical journal indicates that regular meditation may have positive effects on mental well-being.",
      "content": "Sed sollicitudin, ex ut fermentum viverra, libero magna pretium dolor, vitae tincidunt est eros et ligula. Sed ut fermentum mi. Phasellus rutrum tristique sem, at dapibus tortor semper in. Nullam gravida gravida orci, at ultricies metus eleifend non. Praesent tempor, est id malesuada dapibus, eros ligula sollicitudin lorem, at lacinia lorem ligula ac libero. Donec laoreet metus non quam tincidunt, et laoreet justo auctor. Cras faucibus fringilla justo, vitae auctor libero eleifend a. Pellentesque eleifend dolor risus, vitae fringilla mauris faucibus eu. Vivamus non dictum nibh. Donec vitae ante sem. Cras condimentum pharetra sem, at consequat ligula fringilla non.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.2,
      "total_views": 20000
    },
    {
      "id": 3,
      "title": "Tech giants announce collaboration for renewable energy initiatives",
      "category": "National News",
      "author": "David Martinez",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-08",
      "description": "In a joint effort to combat climate change, several major technology companies have pledged to invest in renewable energy projects.",
      "content": "Fusce vitae ligula sed felis volutpat fringilla. Maecenas in dui non magna finibus fringilla. Donec sodales elit non malesuada luctus. Integer rhoncus justo quis efficitur fermentum. Donec ac eros metus. Phasellus eu efficitur libero. Praesent non erat id risus dignissim luctus nec at lorem. Sed nec ultricies est. Nam pellentesque arcu et augue dictum rutrum. In ut nibh risus. Integer vestibulum malesuada lorem nec condimentum. Aliquam scelerisque ligula vel lorem rhoncus aliquet.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.7,
      "total_views": 18000
    },
    {
      "id": 4,
      "title": "Breaking: Earthquake hits California, causing minor damages",
      "category": "Breaking News",
      "author": "Sarah Johnson",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-14",
      "description": "A moderate earthquake struck California today, resulting in minor damages to buildings and infrastructure.",
      "content": "Vestibulum vestibulum, lorem eget suscipit tincidunt, nisi quam vehicula nisi, et fringilla nisl est non eros. Nam scelerisque euismod nisi at lobortis. Integer eget felis eleifend, varius orci in, bibendum arcu. Cras congue nisi vitae ultrices vulputate. In varius tellus non justo fringilla suscipit. Integer non diam at mauris venenatis cursus nec at nisi. Pellentesque sit amet lacus eu augue cursus posuere id quis urna. Cras convallis neque sit amet erat maximus interdum.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.0,
      "total_views": 25000
    },
    {
      "id": 5,
      "title": "New iPhone model rumored to feature advanced camera technology",
      "category": "Breaking News",
      "author": "Michael Brown",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-10",
      "description": "Leaks suggest that the upcoming iPhone model will come equipped with cutting-edge camera features, including improved low-light performance and enhanced zoom capabilities.",
      "content": "Maecenas blandit, turpis ut aliquam posuere, neque sem viverra lorem, vel congue nisi nisl vel lectus. Sed nec metus ligula. Nulla facilisi. Nulla facilisi. Fusce id laoreet ex. Phasellus nec purus vel velit volutpat scelerisque. Sed ac est tincidunt, commodo mi id, laoreet ipsum. Sed lobortis bibendum tellus nec tempus. Nam maximus, dui a gravida dapibus, neque orci ullamcorper velit, nec luctus lorem libero nec nulla.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.3,
      "total_views": 30000
    },
    {
      "id": 6,
      "title": "New archaeological discovery sheds light on ancient civilization",
      "category": "Regular News",
      "author": "Sophia Clark",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-11",
      "description": "Excavations in Egypt reveal artifacts providing insights into the daily life and culture of an ancient civilization.",
      "content": "Praesent id purus neque. Nulla bibendum quam eu feugiat gravida. Suspendisse in nunc nec justo hendrerit ultricies. Nulla auctor erat vel interdum venenatis. Phasellus euismod, libero sed suscipit tristique, mauris mauris convallis ex, in facilisis sapien urna sed odio. Sed id nulla risus. Aliquam nec fermentum risus. Donec id turpis vel orci lacinia tristique vel ut arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.6,
      "total_views": 20000
    },
    {
      "id": 7,
      "title": "FIFA World Cup 2026: Host cities and stadiums announced",
      "category": "International News",
      "author": "Daniel Garcia",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-09",
      "description": "The locations and venues for the 2026 FIFA World Cup have been finalized, with matches set to take place in cities across North America.",
      "content": "Vivamus bibendum est vitae est ultrices, sit amet rhoncus nisi lacinia. Praesent at tellus nec orci ultricies convallis. Nulla id odio est. Proin a dolor id metus varius lacinia id vel elit. Sed laoreet, lacus at pharetra tristique, risus est aliquam urna, vel vehicula ante purus vel nibh. Sed pretium urna sit amet metus fermentum, nec accumsan dolor tempor. Morbi vestibulum, mi in posuere tristique, turpis justo vestibulum risus, non lobortis risus nulla nec est. Sed vehicula, arcu ut ullamcorper lacinia, risus eros ultricies enim, nec elementum tortor mauris nec quam. Integer iaculis sapien vitae sollicitudin luctus. Cras fermentum nunc a mollis finibus.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.4,
      "total_views": 22000
    },
    {
      "id": 8,
      "title": "New blockbuster movie breaks box office records",
      "category": "Entertainment",
      "author": "Olivia Taylor",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-13",
      "description": "The latest film from a renowned director has smashed previous records, becoming the highest-grossing opening weekend in cinema history.",
      "content": "Quisque eu tortor lectus. Cras at viverra elit, eget elementum nunc. Ut condimentum velit id ante condimentum auctor. Vivamus sed ex ut arcu tempor malesuada ac a erat. Sed condimentum augue justo, id ultricies nulla vestibulum a. Nulla facilisi. Nulla facilisi. Morbi molestie purus vel dolor sollicitudin eleifend. Vivamus elementum efficitur ex, vel convallis velit. Phasellus bibendum ante nec tortor sodales, ac gravida justo feugiat. Cras convallis ultricies dolor, nec interdum libero luctus id. Suspendisse feugiat nisi a nulla volutpat, eget malesuada enim volutpat.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.8,
      "total_views": 25000
    },
    {
      "id": 9,
      "title": "New art exhibition showcases emerging talents",
      "category": "Culture",
      "author": "Michael Lee",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-12",
      "description": "A gallery in New York City unveils a collection of works by up-and-coming artists, highlighting diverse perspectives and creative expressions.",
      "content": "Aliquam at elit nunc. Ut varius ipsum ut justo viverra, vel rhoncus justo rhoncus. Morbi eu massa id nibh finibus fermentum. Maecenas non fermentum urna. Nam placerat justo quis interdum vehicula. Nam id nisi ut sem venenatis dictum. Integer et tempor elit, non tristique lacus. Sed a ex ut tellus dignissim molestie. Suspendisse efficitur, mauris ac feugiat gravida, purus justo efficitur justo, non ultricies nulla quam ac elit. Fusce pulvinar ante id mi vulputate, ut eleifend ante consequat.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.5,
      "total_views": 18000
    },
    {
      "id": 10,
      "title": "New theater production receives rave reviews",
      "category": "Arts",
      "author": "Sophia White",
      "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
      "date": "2024-02-11",
      "description": "A groundbreaking play earns critical acclaim for its innovative storytelling and compelling performances.",
      "content": "Vestibulum condimentum non ex at hendrerit. Donec in arcu a ligula gravida consequat. Duis auctor ipsum at tellus iaculis, id tincidunt magna pharetra. Phasellus at orci a nisi laoreet aliquet. Aliquam erat volutpat. Vestibulum lobortis efficitur nulla, non congue lorem lacinia quis. Duis et convallis odio. Integer rutrum odio ex, at dignissim odio pharetra eget. Sed nec eros a odio tempus fringilla a nec odio. Cras porttitor pharetra ligula. Pellentesque lobortis, risus vitae lobortis accumsan, lorem justo varius diam, vel commodo ligula est vel orci. Integer consectetur luctus dui.",
      "image_url": "https://i.ibb.co/1MSTB1Q/regular-news.jpg",
      "rating": 4.6,
      "total_views": 20000
    },
    {
        "id": 11,
        "title": "Tokyo Olympics: Record-breaking performance in swimming",
        "category": "Sports",
        "author": "Alex Johnson",
        "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
        "date": "2024-07-30",
        "description": "A swimmer from Australia sets a new world record in the 100m freestyle event at the Tokyo Olympics, dazzling spectators with their incredible speed and technique.",
        "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac purus ac tellus gravida fringilla. Nam non nunc vel sapien rhoncus aliquet. Sed in sapien ut purus posuere mollis. Nunc non dui aliquet, efficitur sem vitae, volutpat nisi. Proin non magna ac felis lobortis condimentum vel at nisi. Cras at lobortis ex, a pharetra eros. Nulla hendrerit ultricies libero a tempor. Integer in rutrum tortor, ac faucibus libero. Fusce volutpat metus quam, ac malesuada turpis consequat id.",
        "image_url": "https://i.ibb.co/QdVxHX5/sports.jpg",
        "rating": 4.9,
        "total_views": 35000
      },
      {
        "id": 12,
        "title": "UEFA Champions League: Dramatic comeback secures victory",
        "category": "Sports",
        "author": "Sophie Roberts",
        "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
        "date": "2024-05-18",
        "description": "In a thrilling match, a football team stages a remarkable comeback to win the UEFA Champions League final, stunning fans around the world.",
        "content": "Sed sollicitudin, ex ut fermentum viverra, libero magna pretium dolor, vitae tincidunt est eros et ligula. Sed ut fermentum mi. Phasellus rutrum tristique sem, at dapibus tortor semper in. Nullam gravida gravida orci, at ultricies metus eleifend non. Praesent tempor, est id malesuada dapibus, eros ligula sollicitudin lorem, at lacinia lorem ligula ac libero. Donec laoreet metus non quam tincidunt, et laoreet justo auctor. Cras faucibus fringilla justo, vitae auctor libero eleifend a. Pellentesque eleifend dolor risus, vitae fringilla mauris faucibus eu. Vivamus non dictum nibh. Donec vitae ante sem. Cras condimentum pharetra sem, at consequat ligula fringilla non.",
        "image_url": "https://i.ibb.co/QdVxHX5/sports.jpg",
        "rating": 4.7,
        "total_views": 28000
      },
      {
        "id": 13,
        "title": "Rugby World Cup: Exciting final delivers thrilling action",
        "category": "Sports",
        "author": "David Thompson",
        "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
        "date": "2024-11-02",
        "description": "In a closely contested match, the Rugby World Cup final showcases intense competition and skillful plays, keeping fans on the edge of their seats until the final whistle.",
        "content": "Fusce vitae ligula sed felis volutpat fringilla. Maecenas in dui non magna finibus fringilla. Donec sodales elit non malesuada luctus. Integer rhoncus justo quis efficitur fermentum. Donec ac eros metus. Phasellus eu efficitur libero. Praesent non erat id risus dignissim luctus nec at lorem. Sed nec ultricies est. Nam pellentesque arcu et augue dictum rutrum. In ut nibh risus. Integer vestibulum malesuada lorem nec condimentum. Aliquam scelerisque ligula vel lorem rhoncus aliquet.",
        "image_url": "https://i.ibb.co/QdVxHX5/sports.jpg",
        "rating": 4.8,
        "total_views": 32000
      },
      {
        "id": 14,
        "title": "NHL Finals: Cinderella story leads to unexpected victory",
        "category": "Sports",
        "author": "Emily Davis",
        "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
        "date": "2024-06-15",
        "description": "An underdog team defies the odds to win the NHL Finals, capturing the hearts of hockey fans everywhere with their inspiring journey to the championship.",
        "content": "Vestibulum vestibulum, lorem eget suscipit tincidunt, nisi quam vehicula nisi, et fringilla nisl est non eros. Nam scelerisque euismod nisi at lobortis. Integer eget felis eleifend, varius orci in, bibendum arcu. Cras congue nisi vitae ultrices vulputate. In varius tellus non justo fringilla suscipit. Integer non diam at mauris venenatis cursus nec at nisi. Pellentesque sit amet lacus eu augue cursus posuere id quis urna. Cras convallis neque sit amet erat maximus interdum.",
        "image_url": "https://i.ibb.co/QdVxHX5/sports.jpg",
        "rating": 4.9,
        "total_views": 40000
      },
      {
        "id": 15,
        "title": "Formula 1: Thrilling race under the lights in Singapore",
        "category": "Sports",
        "author": "Daniel Johnson",
        "author_url": "https://i.ibb.co/grLPKMc/author.jpg",
        "date": "2024-09-22",
        "description": "The Singapore Grand Prix delivers excitement and drama as drivers navigate the challenging street circuit under the dazzling lights of the city skyline.",
        "content": "Maecenas blandit, turpis ut aliquam posuere, neque sem viverra lorem, vel congue nisi nisl vel lectus. Sed nec metus ligula. Nulla facilisi. Nulla facilisi. Fusce id laoreet ex. Phasellus nec purus vel velit volutpat scelerisque. Sed ac est tincidunt, commodo mi id, laoreet ipsum. Sed lobortis bibendum tellus nec tempus. Nam maximus, dui a gravida dapibus, neque orci ullamcorper velit, nec luctus lorem libero nec nulla.",
        "image_url": "https://i.ibb.co/QdVxHX5/sports.jpg",
        "rating": 4.7,
        "total_views": 35000
      }
  ]
  